config/routes.rb
Rails.application.routes.draw do
  get 'characters/index'
  get 'characters/:name', to: 'characters#show', as: 'character', name: %r{([^/])+?}
  get 'characters/', to: 'characters#index', as: 'characters'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'seasons#home'
  get 'episodes/:id', to: 'episodes#show', as: 'episode'
  get 'seasons/:serie/:id', to: 'seasons#show', as: 'season'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def show
    name = params[:name].split('%')
    ur = name.join('+')
    url_character = 'https://tarea-1-breaking-bad.herokuapp.com/api/characters/?name=%s' % ur
    response = HTTP.get(url_character)
    if response.status.success?
      @character = JSON.parse(response)[0]
      if @character.nil?
        redirect_to root_path, alert: 'Character Not Found'
      else
        url_quote = 'https://tarea-1-breaking-bad.herokuapp.com/api/quote?author=%s' % ur
        @quotes = JSON.parse(HTTP.get(url_quote))
      end
    elsif response.code == 429
      redirect_to root_path, alert: 'Too Many Requests'
    else
      redirect_to root_path, alert: 'Character Not Found'
    end
  end

  def index
    search(params[:search])
    if $search_characters.nil?
      redirect_to root_path, alert: 'Character Not Found'
    else
      @busqueda = $search_characters
    end
  end

  def search(s)
    if s
      name = params[:search].split(' ')
      ur = name.join('+')
      url_characters = 'https://tarea-1-breaking-bad.herokuapp.com/api/characters/?name=%s' % ur
      chars = HTTP.get(url_characters)
      if chars.status.success?
        $search_characters = JSON.parse(chars)
        if $search_characters.empty?
          redirect_to root_path, alert: 'Character Not Found'
        end
        if $search_characters.count == 10
          a = 1
          b = a * 10
          url = url_characters + '&limit=10&offset=%d' % b
          cha = HTTP.get(url)
          if cha.status.success?
            char =JSON.parse(cha)
            $search_characters = ($search_characters << char).flatten!
            while char.count == 10
              a += 1
              b = a * 10
              url = url_characters + '&limit=10&offset=%d' % b
              cha = HTTP.get(url)
              if cha.status.success?
                char = JSON.parse(cha)
                $search_characters = ($search_characters << char).flatten!
              elsif cha.code == 429
                redirect_to root_path, alert: 'Too Many Requests'
              end
            end
          elsif cha.code == 429
            redirect_to root_path, alert: 'Too Many Requests'
          end
        end
      elsif chars.code == 429
        redirect_to root_path, alert: 'Too Many Requests'
      else
        redirect_to root_path, alert: 'Character Not Found'
      end
    end
  end

  private

  def char_params
    params.permit(:name, :search)
  end
end

app/controllers/episodes_controller.rb
require 'http'
require 'json'

class EpisodesController < ApplicationController
  before_action :calendario, only: %i[show]
  
  def calendario
    $calendario = {'01' => 'January', '02' => 'February', '03' => 'March', '04' => 'April', '05' => 'May',
                   '06' => 'June', '07' => 'July', '08' => 'August', '09' => 'September', '10' => 'October', 
                   '11' => 'November', '12' => 'December'}
  end
  
  def show
    url_episode = 'https://tarea-1-breaking-bad.herokuapp.com/api/episodes/'
    id_episodio = params[:id]
    url = url_episode + id_episodio
    response = HTTP.get(url)
    if response.status.success?
      @episode = JSON.parse(response)[0]
      if @episode.nil?
        redirect_to root_path, alert: 'Episode Not Found'
      else
        @serie = @episode['series']
        fecha = (@episode['air_date'].split('T')[0]).split('-')
        @date = '%s %s, %s' %[fecha[2], $calendario[fecha[1]], fecha[0]]
      end
    elsif response.code == 429
      redirect_to root_path, alert: 'Too Many Requests'
    else
      redirect_to root_path, alert: 'Episode Not Found'
    end
  end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  before_action :get_episodios, only: %i[home show]

  def home
  end

  def show
    @episodios = {}
    if params[:serie] == "BB"
      @temp = $temporadas_bb[params[:id]]
      if @temp.nil?
        redirect_to root_path, alert: 'Season Not Found'
      else
        @serie = "Breaking Bad"
        $response_episodios_bb.each do |episode|
          @episodios[episode["title"]] = episode["episode_id"]
        end
      end
    elsif params[:serie] == "Saul"
      @serie = "Better Call Saul"
      @temp = $temporadas_saul[params[:id]]
      if @temp.nil?
        redirect_to root_path, alert: 'Season Not Found'
      else
        $response_episodios_saul.each do |episode|
          @episodios[episode["title"]] = episode["episode_id"]
        end
      end
    else
      redirect_to root_path, alert: 'TV Series Not Found'
    end
  end

  def get_episodios
    url_episodes_breaking_bad = 'https://tarea-1-breaking-bad.herokuapp.com/api/episodes?series=Breaking+Bad'
    url_episodes_better_call_saul = 'https://tarea-1-breaking-bad.herokuapp.com/api/episodes?series=Better+Call+Saul'
    $response_episodios_bb = JSON.parse(HTTP.get(url_episodes_breaking_bad).body)
    $response_episodios_saul = JSON.parse(HTTP.get(url_episodes_better_call_saul).body)
    $temporadas_bb = {}
    $response_episodios_bb.each do |episode|
      if $temporadas_bb.has_key?(episode["season"])
        $temporadas_bb[episode["season"]].append(episode["title"])
      else
        $temporadas_bb[episode["season"]] = []
        $temporadas_bb[episode["season"]].append(episode["title"])
      end
    end
    $temporadas_saul = {}
    $response_episodios_saul.each do |episode|
      if $temporadas_saul.has_key?(episode["season"])
        $temporadas_saul[episode["season"]].append(episode["title"])
      else
        $temporadas_saul[episode["season"]] = []
        $temporadas_saul[episode["season"]].append(episode["title"])
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/episode_helper.rb
module EpisodeHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/characters/index.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1" xmlns="http://www.w3.org/1999/html">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
<section class="hero is-link">
  <div class="hero-body">
    <div class="container">
      <nav class="level">
        <div class="level-left">
          <div class="level-item">
            <h1 class="title">Tarea 1: Consumir una API</h1>
          </div>
        </div>
        <div class="level-right">
          <div class="level-item">
            <%= link_to('Home', root_path, :class => "button is-link is-inverted") %>
          </div>
        </div>
      </nav>
    </div>
  </div>
</section>
<section class="section">
  <div class="container">
    <nav class="level">
      <div class="level-item">
        <%= form_tag characters_index_path, :method => "get" do %>
          <%= label_tag :search, "Character Search" %>
          <%= text_field_tag :search, params[:search], :placeholder => "Type your search" %>
          <%= submit_tag  "Search", :name => nil%>
        <%end %> <br>
      </div>
    </nav>
    <div class="level">
      <div class="level-item">
        <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
      </div>
    </div>
  </div>
</section>
<section class="section">
  <div class="container">
    <article class="media">
      <figure class="media-left">
        <p class="image is-128x128">
          <%= image_tag("https://pics.freeicons.io/uploads/icons/png/3973644001582960208-512.png") %>
        </p>
      </figure>
      <div class="media-content">
        <div class="content">
          <p>
          <h1> Character Search Results </h1>
          <br>
          <% i = 1 %>
          <%@busqueda.each do |char| %>
            <td><%="%d." % i%></td> <td> <%= link_to char["name"], character_path(char["name"].gsub(/\s+/, "%")) %> </td><br>
            <%i+= 1 %>
          <% end %>
          <br>
          </p>
        </div>
      </div>
    </article>
  </div>
</section>
<section class="section">
  <nav class="level-left">
    <div class="level-item">
        <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
      <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
    </div>
  </nav>
</section>
<footer class="footer">
  <div class="container">
    Copyright © 2021 Tarea 1 Antonia Christensen. All rights reserved.
    <div class="level-right">
      <p class="level-item">
      </p>
    </div>
  </div>
</footer>

app/views/layouts/_alerts.html.erb
<%if notice %>
  <div id="notice_wrapper">
    <p class="notice"><%= notice %></p>
  </div>
<%elsif alert %>
  <div id="alert_wrapper">
    <p class="alert"><%= alert %></p>
  </div>
<%end %>

app/views/layouts/application.html.erb
<!--Sacado de https://www.youtube.com/watch?reload=9&v=87fBAWc25Sk-->
<!DOCTYPE html>
<html>
  <head>
    <title>T1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application", 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/alerts' %>
    <%= yield %>

  <script>
      $(document).ready(function() {
          setTimeout(function () {
              $('#notice_wrapper').fadeOut("slow", function () {
                  $(this).remove();
              })
          }, 1000);
      });
      $(document).ready(function() {
          setTimeout(function(){
              $('#alert_wrapper').fadeOut("slow", function() {
                  $(this).remove();
              })
          }, 1000);
      });
  </script>
  </body>
</html>

app/views/seasons/home.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1" xmlns="http://www.w3.org/1999/html">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
<section class="hero is-link">
  <div class="hero-body">
    <div class="container">
      <nav class="level">
        <div class="level-left">
          <div class="level-item">
            <h1 class="title">Tarea 1: Consumir una API</h1>
          </div>
        </div>
        <div class="level-right">
          <div class="level-item">
            <%= link_to('Home', root_path, :class => "button is-link is-inverted") %>
          </div>
        </div>
      </nav>
    </div>
  </div>
</section>
<section class="section">
  <div class="container">
    <nav class="level">
      <div class="level-item">
        <%= form_tag characters_index_path, :method => "get" do %>
          <%= label_tag :search, "Character Search" %>
          <%= text_field_tag :search, params[:search], :placeholder => "Type your search" %>
          <%= submit_tag  "Search", :name => nil%>
        <%end %> <br>
      </div>
    </nav>
    <div class="level">
      <div class="level-item">
        <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-warning">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-danger">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-info">
          <i class="fas fa-atom"></i>
        </span>
        <span class="icon has-text-success">
          <i class="fas fa-atom"></i>
        </span>
      </div>
    </div>
  </div>
</section>
<section class="section">
  <div class="container">
    <nav class="level">
      <div class="level-item">
        <article class="media">
          <figure class="media-left">
            <p class="image is-128x128">
              <%= image_tag("https://m.media-amazon.com/images/M/MV5BMjhiMzgxZTctNDc1Ni00OTIxLTlhMTYtZTA3ZWFkODRkNmE2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg") %>
            </p>
          </figure>
          <div class="media-content">
            <div class="content">
              <p>
              <h1> Breaking Bad </h1> <h4>Seasons</h4>
              <% $temporadas_bb.each_key do |temp| %>
                <td><%= link_to "Season %d" % temp, season_path("BB",temp)%></td> <br>
              <% end %>
              <br>
              </p>
            </div>
          </div>
        </article>
      </div>
      <div class="level-item">
        <article class="media">
          <figure class="media-left">
            <p class="image is-128x128">
              <%= image_tag("https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSPGTwuT0Wg5XHC71WlpvmHInG00hkhDd4SiUGNjlQALyvgr6Fh") %>
            </p>
          </figure>
          <div class="media-content">
            <div class="content">
              <p>
              <h1> Better Call Saul </h1> <h4>Seasons</h4>
              <% $temporadas_saul.each_key do |temp| %>
                <td><%= link_to "Season %d" % temp, season_path("Saul",temp)%></td> <br>
              <% end %>
              <br>
              </p>
            </div>
          </div>
        </article>
      </div>
    </nav>
  </div>
</section>
<footer class="footer">
  <div class="container">
    Copyright © 2021 Tarea 1 Antonia Christensen. All rights reserved.
    <div class="level-right">
      <p class="level-item">
      </p>
    </div>
  </div>
</footer>